version: '3.8'

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/data/postgres

  api:
    build: 
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 3333:3333
    volumes:
      - ./apps/api:/usr/src/app
    links:
      - database
    depends_on:
      - database

  bot:
    build:
      context: ./apps/bot
      dockerfile: Dockerfile
    container_name: bot
    ports:
      - 3000:3000
    volumes:
      - ./apps/bot:/usr/src/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local